"""Versioned, replay-safe Momentum domain contracts.

Feature-driven engines, the state reducer, and the in-memory projection live in
explicit submodules.  This package surface exposes only dependency-free model
contracts; broker actions remain outside the Momentum domain.
"""

from signals.models import (
    EntryMode,
    EntryOpportunity,
    EntryOpportunityStatus,
    EntryPolicyDecision,
    EntryRiskLevel,
    EpisodeStatus,
    EvidenceStatus,
    SignalDetail,
    EvidenceUpdate,
    MomentumEntryPolicyConfig,
    MomentumEpisode,
    MomentumSignal,
    MomentumStage,
    RiskGateStatus,
    SignalEvaluationStatus,
    SignalFamily,
    SignalResult,
    StageTransition,
    evaluate_momentum_entry_opportunity,
    evaluate_momentum_entry_policy,
)
from signals.decision_evidence import (
    DecisionEvidence,
    DecisionEvidenceEnvelope,
    RetroactiveLabel,
    StructuralCompleteness,
    decode_decision_evidence,
    encode_decision_evidence,
)
from signals.entry_specification import (
    AblationCohortPlan,
    CandidateSetEvidenceRequirement,
    EntrySpecification,
    ExecutionBinding,
    FalsifyingCase,
    HardPredicate,
    RequiredDatum,
    ScoreThreshold,
    ScoredEvidence,
    SelectionPolicyRef,
    Split,
    StageGate,
)
from signals.gate_taxonomy import (
    GATE_DECLARATIONS,
    GATE_TAXONOMY_DIGEST,
    FalsifyingCaseKind,
    GateClass,
    GateDeclaration,
    RemediationStatus,
    get_gate_declaration,
)
from signals.selection import (
    LEGACY_ATOMIC_V0,
    LEGACY_MOMENTUM_V0,
    CandidateSetEvidence,
    RankedCandidate,
    SelectionCandidate,
    SelectionContractError,
    SelectionPolicy,
    SelectionReason,
    SelectionResult,
    SortKey,
    candidate_set_digest,
    select,
)

__all__ = [
    "AblationCohortPlan",
    "CandidateSetEvidence",
    "CandidateSetEvidenceRequirement",
    "DecisionEvidence",
    "DecisionEvidenceEnvelope",
    "EntryMode",
    "EntryOpportunity",
    "EntryOpportunityStatus",
    "EntryPolicyDecision",
    "EntryRiskLevel",
    "EntrySpecification",
    "EpisodeStatus",
    "EvidenceStatus",
    "EvidenceUpdate",
    "ExecutionBinding",
    "FalsifyingCase",
    "FalsifyingCaseKind",
    "GATE_DECLARATIONS",
    "GATE_TAXONOMY_DIGEST",
    "GateClass",
    "GateDeclaration",
    "HardPredicate",
    "LEGACY_ATOMIC_V0",
    "LEGACY_MOMENTUM_V0",
    "MomentumEntryPolicyConfig",
    "MomentumEpisode",
    "MomentumSignal",
    "MomentumStage",
    "RiskGateStatus",
    "RankedCandidate",
    "RemediationStatus",
    "RequiredDatum",
    "RetroactiveLabel",
    "ScoreThreshold",
    "ScoredEvidence",
    "SelectionCandidate",
    "SelectionContractError",
    "SelectionPolicy",
    "SelectionPolicyRef",
    "SelectionReason",
    "SelectionResult",
    "SignalEvaluationStatus",
    "SignalFamily",
    "SignalDetail",
    "SignalResult",
    "SortKey",
    "Split",
    "StageGate",
    "StageTransition",
    "StructuralCompleteness",
    "candidate_set_digest",
    "decode_decision_evidence",
    "encode_decision_evidence",
    "evaluate_momentum_entry_opportunity",
    "evaluate_momentum_entry_policy",
    "get_gate_declaration",
    "select",
]
